//
// Created by Timothy Shull on 12/6/15.
//

#ifndef CPPLANGUAGE_CONSTRUCTION_CLEANUP_COPY_AND_MOVE_H
#define CPPLANGUAGE_CONSTRUCTION_CLEANUP_COPY_AND_MOVE_H

#include <string>

#endif //CPPLANGUAGE_CONSTRUCTION_CLEANUP_COPY_AND_MOVE_H
