//
// Created by Timothy Shull on 12/1/15.
//

#ifndef CPPLANGUAGE_POINTERS_ARRAYS_AND_REFERENCES_H
#define CPPLANGUAGE_POINTERS_ARRAYS_AND_REFERENCES_H

char *return_char_pointer(char &);

#endif //CPPLANGUAGE_POINTERS_ARRAYS_AND_REFERENCES_H
